changing logic around for clearer workflow

diff --git a/docker-helper b/docker-helper
--- a/docker-helper
+++ b/docker-helper
@@ -6,38 +6,19 @@ CMD="$1"
 
 login()
 {
-
-
-    # if aws_profile
-        # aws login
-    
-    # if dockerhub vars set
-        # login dockerhub
-
-    # if github_user set
-        # login to github 
-
-    if [ -z "${AWS_PROFILE:-}" ]; then
-        echo "Using Docker Hub login"
-        if [ -z "${DOCKER_USER:-}" ] || [ -z "${DOCKER_PASS:-}" ]; then
-            echo "Please set DOCKER_USER and DOCKER_PASS environment variables."
-            exit 1
-        fi
-        docker login -u $DOCKER_USER -p $DOCKER_PASS
-    else
-        echo "Using ECR login"
+    if ! [ -z "${AWS_PROFILE:-}" ]; then
+        echo "ECR login in progress"
         $(aws ecr get-login --no-include-email)
     fi
 
-    # Attempt to authenticate into github package registry
-    echo "Authenticating on Github. Will peacefully exit if not set up yet."
-    if [ -z "${GITHUB_USERNAME:-}" ] || [ -z "${GITHUB_TOKEN:-}" ]; then
-        echo "Please set GITHUB_USERNAME and GITHUB_TOKEN environment variables."
-    else
+    if ! [ -z "${DOCKER_USER:-}" ] || [ -z "${DOCKER_PASS:-}" ]; then
+        echo "Dockerhub login in progress"
+        docker login -u $DOCKER_USER -p $DOCKER_PASS
+    fi
+
+    if ! [ -z "${GITHUB_USERNAME:-}" ] || [ -z "${GITHUB_TOKEN:-}" ]; then
+        echo "Github login in progress"
         docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
-        if [$? -ne 0]; then
-            echo "Authenticating to Github failed"
-        fi
     fi
 }
 
@@ -62,35 +43,36 @@ case $CMD in
         docker tag $CI_TAG $REPO:"sha-$COMMIT"
         docker tag $CI_TAG $REPO:"branch-$BRANCH"
         docker tag $CI_TAG $REPO:"build-$BUILD_NUMBER"
+
         # if github token set
-        docker tag $CI_TAG $GITHUB_REPO:"sha-$COMMIT"
-        docker tag $CI_TAG $GITHUB_REPO:"branch-$BRANCH"
-        docker tag $CI_TAG $GITHUB_REPO:"build-$BUILD_NUMBER"
-        # end if
+        if ! [ -z "${GITHUB_USERNAME:-}" ] || [ -z "${GITHUB_TOKEN:-}" ]; then
+            docker tag $CI_TAG $GITHUB_REPO:"sha-$COMMIT"
+            docker tag $CI_TAG $GITHUB_REPO:"branch-$BRANCH"
+            docker tag $CI_TAG $GITHUB_REPO:"build-$BUILD_NUMBER"
+        fi
     ;;
     push)
-        # push to dockerhub
         REPO="$2"
-
-        # if aws_profile
-            # push aws
-        
-        # if dockerhub vars set
-            # push dockerhub
-
-        # if github_user set
-            # push to github 
-
-        login
-        docker push $REPO
-
-        # attempt to push to github registry
         PROJ_NAME=$(basename $REPO)
         GITHUB_REPO="docker.pkg.github.com/$REPO/$PROJ_NAME"
-        docker push $GITHUB_REPO
-        if [ $? -ne 0 ]; then
-            echo "Push to $GITHUB_REPO failed"
+
+        login
+
+        # if dockerhub vars set, push dockerhub
+        if ! [ -z "${DOCKER_USER:-}" ] || [ -z "${DOCKER_PASS:-}" ]; then
+            echo "Pushing to Dockerhub"
+            docker push $REPO
         fi
+
+        # if github_user set, push to github
+        if ! [ -z "${GITHUB_USERNAME:-}" ] || [ -z "${GITHUB_TOKEN:-}" ]; then
+            echo "Pushing to Github Package Registry"
+            docker push $GITHUB_REPO
+            if [ $? -ne 0 ]; then
+                echo "Push to $GITHUB_REPO failed"
+            fi
+        fi
+
     ;;
     *)
         echo "Unknown command $CMD"
